name: CI Workflow for React and Spring Boot

on:
  push:
    branches:
      - master
    paths:
      - "journal-app-react/**" # Frontend folder
      - "journalapp/**" # Backend folder
      - ".vscode/**" # Changes in parent folder
      - "README.md" # Changes in README or root-level files
      - ".github/**"
  pull_request:
    branches:
      - master
    paths:
      - "journal-app-react/**"
      - "journalapp/**"
      - ".vscode/**"
      - "README.md"
      - ".github/**"

jobs:
  frontend-build:
    if: contains(github.event.commits.modified , '.github/')


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20] # Version for Node.js/React

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for React
        working-directory: ./journal-app-react
        run: npm install

      - name: Build React app
        working-directory: ./journal-app-react
        run: npm run build

  backend-build:
    if: |
      github.event_name == 'push' && (
        contains(github.event.head_commit.message, 'journalapp') ||
        contains(github.event.head_commit.message, '.vscode') ||
        contains(github.event.head_commit.message, 'README.md') ||
        contains(github.event.head_commit.message, '.github')
      ) ||
      github.event_name == 'pull_request' && (
        contains(github.event.pull_request.changed_files, 'journalapp') ||
        contains(github.event.pull_request.changed_files, '.vscode') ||
        contains(github.event.pull_request.changed_files, 'README.md') ||
        contains(github.event.pull_request.changed_files, '.github')
      )
        
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        java-version: [21] # Version for Java (eclipse-temurin:21 in Docker)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java for Spring Boot
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: Build Spring Boot app
        working-directory: ./journalapp
        run: ./mvnw clean install

      - name: Run Spring Boot tests
        working-directory: ./journalapp
        run: ./mvnw test

      - name: Build Docker image for backend
        working-directory: ./journalapp
        run: docker build -t chetankansal/journalserverapp:latest .

      - name: Push Docker image to Docker Hub
        run: docker push chetankansal/journalserverapp:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
