name: CI Workflow for React and Spring Boot

on:
  push:
    branches:
      - master
    paths:
      - "journal-app-react/**" # Frontend folder
      - "journalapp/**" # Backend folder
      - ".vscode/**" # Changes in parent folder
      - "README.md" # Changes in README or root-level files
      - ".github/**"
  pull_request:
    branches:
      - master
    paths:
      - "journal-app-react/**"
      - "journalapp/**"
      - ".vscode/**"
      - "README.md"
      - ".github/**"

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for modified frontend files
        id: check_modified_frontend
        run: |
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "MODIFIED_FILES=${MODIFIED_FILES}" >> $GITHUB_ENV

      - name: Set up Node.js
        if: contains(env.MODIFIED_FILES, '.github/')
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the required Node.js version

      - name: Install dependencies
        if: contains(env.MODIFIED_FILES, 'journal-app-react/')
        working-directory: ./journal-app-react
        run: npm install

      - name: Build React app
        if: contains(env.MODIFIED_FILES, 'journal-app-react/')
        working-directory: ./journal-app-react
        run: npm run build

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for modified backend files
        id: check_modified_backend
        run: |
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "MODIFIED_FILES=${MODIFIED_FILES}" >> $GITHUB_ENV

      - name: Set up Java
        if: contains(env.MODIFIED_FILES, 'journalapp/')
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build Spring Boot app
        if: contains(env.MODIFIED_FILES, 'journalapp/')
        working-directory: ./journalapp
        run: ./mvnw clean install

      - name: Build Docker image for backend
        if: contains(env.MODIFIED_FILES, 'journalapp/')
        working-directory: ./journalapp
        run: docker build -t chetankansal/journalserverapp:latest .

      - name: Push Docker image to Docker Hub
        if: contains(env.MODIFIED_FILES, 'journalapp/')
        working-directory: ./journalapp
        run: docker push chetankansal/journalserverapp:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
